sudo: false
language: node_js
matrix:
  include:
  - node_js: '0.12'
  - node_js: '4'
  - node_js: '5'
  - node_js: '6'
  - node_js: '6'
    env: BROWSER=true
before_script:
- npm install -g coveralls@2.11.12
script:
- if [[ "${BROWSER}" == "true" ]]; then travis_retry travis_wait npm run browser-test;
  else npm run -s travis-test; fi
env:
  global:
  - secure: YbWnE8nXFcBCsb3kuzVH7RLSKGjWIV/ZFsK0xcyXfjA9qCitFygzoRljSd10QTDpMs7ow2E4T8nPvhO2r7zu0JdEgEPLLqbXH7q6PPw9PiM8SnFngmitpdfJ0jke0D17I1nBj3nXvvQGPKGhSFJAOnJPL7HdiArBsu16WSBqdj6n5k6d6kxLmX/+/Fu4XxoEAeqEGttKB7hxfBtjxgwOBB5roQuBMQ4BNVyDd6rDh7rCkTHBKikzAsFdofYJ0J/x7V9LcxjKp/oIWYUu4AekecXrb2QLvI4Fsj1gnzu6B5wqEuaQf7q5eXqim9BNLrlIo5V2KUb8M2YzuzkIcLEmdbIhBqA4/+V2HfEfBvGNrE1XCtgCuT2KPVauw9CXsqnTIshYm09NpsnO5YLUpiAdUhLaEaB+URcCTr3bQbb26IoPrvqMux1/GUhkkIcdJkdPKikSD21wLLZkbP0sgtP3/bPXwuhdB7dnfCgmi4a57s1DnZLfhWsUWBRT3WTy7J6OLKYaKulG0l4mk907aCTIZ/NRfiGuo+MK9DIpJtvSq2BQgk6x2pl6fGvIsiAPTYekElTe/IaFCP8/DQuiDF3FgDJvCvwkXavz8mYBnt2QkYfi3dEa54FKgYH/Dx68h0AQrDMeelGZb/1In3kOVhMJokuuyN/FnIAf5JrD5oFiVOE=
  - secure: Zu+Tnb3uo4IjbuDofEpY0SbbdY2R70skmIIbFTKozkkgvmBKBJKL/Pl+5ZEJdWBnPfrwQsQMQSzfPf7o5z/NAVuou/pNd2Xgqy0NGRRos/cBv1hw7Pu+3mS/Gayy3E+iC/vKuD4nx0lTMnOitaif2q2pD6FkLWCEJ/rridKoQta5Hz/LzEhHEolrmFB+N1EVwMX0VI7XJkVlK675wlvFRfUyAbmbI3V6as+AmPqqWZu/Z2tSe6vh97C9QGjoNErkUEioWWbOk0VGHeUlLGektKTGoSR/BtghvFldWzQd+qaiIWAJa1YD3AQXsonxyrh5WQI92zIGkB24Pu4snN1fRMg0rKMpQn1S2dDStQAEOvZlfG0WCpZhsO4mP0N8/32LXyxFjZFDUGTAb0TZts+X4jLxR7l3dJ6x+gv8WI5RWtiQACfVyXkicvwTcaqEloF03422j7DlkymkYCPKdCP7nMRLGmhYtJ1CsUxmZPCiLL8Jj065U31DDVu8ncYAWgSJwg+AsG/eWJK8BHKj9bFr4HwAwlXQFVNykiXTWxRfcZqjiLiW+c290y0lZhaiMgxYI/pK4IQ8LHNyT4uezHqxYx+qOwtkbMtPzDdgTIIHenYYrxRvyA9nmdw6cze4RLmxHGsgO4nG/V84J6yFzgZFQiJv26EVGSQxz+aiMWXnBv4=
  - secure: lHyBeifJqaiS/wla1rzCNp4tnRFnZFqzEMHu0Pyi2IjaKGpXnxO6RPSZ9c/Lc2Yd7IHcgOZx5hjKCtvUfwZXTGwhFJVB3SgrpFRZNavh4Q7z//RmOO0AJwJ9uSvBtK2vzlUEQD0mXAAj76isdeUF1mbmJuaN/ySmY0R5y1ZdSUxVZnA0XcNUsRBXGflRnQsBU1kMyn694+LWjSGja593dswOJXBkJ30UEmsa6kUdPd30MnyyVg6jlg72rFWiZTlzE+ySNlTchJD42RFhEUmUEP/Gu1i59Y29BA9dxSTVEFe8D+MIu2jPiDSYFRqDMFXdw7Dvj1NGIUJxQ9XyTGk58F4CTRNwaDWXvzRc5Qk+1wV1UGbU4JGEJX178lubkQYjWF2cCuIquPJoz2xs3r8pvo9Stsl434eNLSK5Ycinuy43dLCzpeARRXLLjJYKFMKh93KHZQZgQmdhxBRK6HzmcpOBl1IgQbsCsjTZ+SGD/aNs17mqOugpPc21zT/+rG3AcRsM6rBlXeodY/aKx3FO4amiGPG5Y/txZlTf4LUNwrzdGaFDmjbcUigcY+ubHVS4PpFGX1vgrbdPN4FDErsU78NdcCJ1BULDvLW/a1sNQbqXhKRZDCL/eDpy0m5FwTJ0MxgI589YaBVgPg5P/G+5RsBVDcr3iOQ9QyT+sh979es=
