ui: tape
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: 6..latest
  - name: ie
    version: 9..latest
  - name: firefox
    version: 40..latest
  - name: opera
    version: 11..latest
  - name: ipad
    version: 8.1..latest
  - name: iphone
    version: 8.1..latest
  - name: android
    version: 4.0..latest
